front_config = {
    'enum_obstacle1': {0: 'car', 1: 'truck', 2: 'bus', 3: 'pedestrian', 4: 'bicycle', 5: 'motorcycle',
                      6: 'tricycle',7: 'misc',8:'cone', 9:'barrier', 10:'safety-crash-barrels',
                      11:'tripod', 12:'traffic_light', 13:'traffic_sign',14:'parking_lock',15:'wheel'},
    'enum_obstacle2': {'car':1, 'truck': 2, 'bus':3,  'pedestrian':4,  'bicycle':5,  'motorcycle':6,
                       'tricycle':7, 'misc':8, 'cone':9, 'barrier':10, 'barrel':11,
                       'tripod':12, 'traffic_light':13, 'traffic_sign':14, 'parking_lock':15, 'wheel':16},
    'enum_obstacle3': {1: 'car', 2: 'truck', 3: 'bus', 4: 'pedestrian', 5: 'bicycle', 6: 'motorcycle',
                      7: 'tricycle',8: 'misc',9:'cone', 10:'barrier', 11:'safety-crash-barrels',
                      12:'tripod', 13:'traffic_light', 14:'traffic_sign',15:'parking_lock',16:'wheel',17:'speed_bump',18:'stop_block'},
    'enum_obstacle4': {'car':0, 'truck': 1, 'bus':2,  'pedestrian':3,  'bicycle':4,  'motorcycle':5,
                       'tricycle':6, 'misc':7, 'cone':8, 'barrier':10, 'barrel':11,
                       'tripod':12, 'traffic_light':13, 'traffic_sign':14, 'parking_lock':15, 'wheel':16},
    'camera_position':{1:'front_far',2:'front_near',3:'back_middle',4:'side_left_rear',5:'side_left_front',6:'side_right_front',\
                    7:'side_right_rear',8:'fish_left',9:'fish_front',10:'fish_right',11:'fish_back'},
    'enum_tl_shape_type':{
        "circle":0,
        "arrow":1,
        "pedestrian":2,
        "bicycle":3,
        "off":4,
        "unknown":5
    },
    'enum_tl_direct':{
        "unknown":0,
        "allow":1,
        "forbid":2,
        "wait":3
    },
    'enum_tl_value_2_direct':{
        0:"unknown",
        1:"allow",
        2:"forbid",
        3:"wait"
    },
    'enum_tsr': {
        0: 'warning_kid',
        1: 'warning_pedestrian',
        2: 'warning_construction',
        3: 'crossroad',
        4: 'left_road_merge',
        5: 'right_road_merge',
        6: 'no_entry',
        7: 'no_stopping',
        8: 'no_waiting',
        9: 'no_parking',
        10: 'stop',
        11: 'no_motor_entry',
        12: 'no_left',
        13: 'no_right',
        14: 'no_straight',
        15: 'no_turn',
        16: 'no_overtaking',
        17: 'allow_overtaking',
        18: 'no_horn',
        19: 'roundabout',
        20: 'yield',
        21:'change_route_left',
        22:'change_route_right',
        23:'induction_left',
        24:'induction_right',
        25:'left_road_closure',
        26:'right_road_closure',
        27:'middle_road_closure',
        28:'road_closure',
        29:"speed_limit5",
        30:"speed_limit10",
        31:"speed_limit20", 
        32:"speed_limit30", 
        33:"speed_limit40",
        34:"speed_limit50", 
        35:"speed_limit60",
        36:"speed_limit70", 
        37:"speed_limit80", 
        38:"speed_limit90", 
        39:"speed_limit100", 
        40:"speed_limit110",
        41:"speed_limit120",
    }

}
eq4_config = {
    "obs_type":{
        0:"car",
        1:"truck",
        2:"bike",
        3:"bicycle",
        4:"pedestrian",
        5:"general_object",
        6:"animal",
        7:"uncertain_vcl",
    }
}
